version: "3"
services:
  web:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./db:/var/www/db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html